# linter: http://lint.travis-ci.org/
language: ruby
sudo: false
bundler_args: --without development
cache:
  bundler: true
  directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec puppet --version
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.7
  - 2.3.3
env:
  global:
    - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"
  matrix:
    - PUPPET_VERSION="~> 3.4.0"
    - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.8.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
    - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
matrix:
  include:
    - rvm: 2.4.0
      dist: trusty
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-3.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.4.0
      dist: trusty
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-4.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
    - rvm: 2.2.7
      env: PUPPET_VERSION="~> 3.4.0"
    - rvm: 2.2.7
      env: PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.2.7
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.2.7
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.4.0"
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
